"""CLI entry point for AetherFusion."""

import argparse
import json
import sys
from pathlib import Path

from aetherfusion import __version__
from aetherfusion.scanner.project_analyzer import ProjectAnalyzer
from aetherfusion.reporter.markdown_reporter import generate_report
from aetherfusion.reporter.json_reporter import generate_json_map, write_json_map
from aetherfusion.reporter.plan_markdown_reporter import generate_plan_report
from aetherfusion.reporter.plan_json_reporter import write_plan_json
from aetherfusion.reporter.patch_markdown_reporter import generate_patch_report
from aetherfusion.reporter.patch_json_reporter import write_patch_json
from aetherfusion.reporter.diff_reporter import generate_diff
from aetherfusion.reporter.apply_json_reporter import write_apply_json
from aetherfusion.reporter.apply_markdown_reporter import generate_apply_report
from aetherfusion.planner.fusion_planner import generate_fusion_plan
from aetherfusion.patcher.dry_run_patch_generator import generate_dry_run_patch
from aetherfusion.applier.safe_apply import apply_patch
from aetherfusion.rollback.safe_rollback import rollback_apply
from aetherfusion.reporter.rollback_json_reporter import write_rollback_json
from aetherfusion.reporter.rollback_markdown_reporter import generate_rollback_report
from aetherfusion.verifier.verify_runner import run_verify
from aetherfusion.reporter.verify_json_reporter import write_verify_json
from aetherfusion.reporter.verify_markdown_reporter import generate_verify_report
from aetherfusion.repair.repair_planner import generate_repair_plan
from aetherfusion.reporter.repair_json_reporter import write_repair_json
from aetherfusion.reporter.repair_markdown_reporter import generate_repair_report
from aetherfusion.importfix.import_fix_planner import generate_import_fix_plan
from aetherfusion.reporter.import_fix_json_reporter import write_import_fix_json
from aetherfusion.reporter.import_fix_markdown_reporter import generate_import_fix_report
from aetherfusion.dependency.dependency_planner import generate_dependency_plan
from aetherfusion.reporter.dependency_json_reporter import write_dependency_json
from aetherfusion.reporter.dependency_markdown_reporter import generate_dependency_report
from aetherfusion.audit.audit_logger import (
    log_audit_event, make_apply_event, make_rollback_event,
    make_verify_event, make_repair_plan_event, make_import_fix_plan_event,
    make_dependency_plan_event,
)
from aetherfusion.session.session_runner import run_fusion_session
from aetherfusion.git_checker import check_git_status


def main(argv: list[str] | None = None) -> None:
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="aetherfusion",
        description=f"AetherFusion — Local Code Project Fusion Tool v{__version__}",
    )
    parser.add_argument(
        "--version", action="version", version=f"aetherfusion {__version__}"
    )
    subparsers = parser.add_subparsers(dest="command", help="Sub-commands")

    # scan command
    scan_parser = subparsers.add_parser("scan", help="Scan two projects and generate a fusion report")
    scan_parser.add_argument(
        "--source",
        required=True,
        type=str,
        help="Path to the source project (project-b) to merge from.",
    )
    scan_parser.add_argument(
        "--target",
        required=True,
        type=str,
        help="Path to the target project (project-a) to merge into.",
    )
    scan_parser.add_argument(
        "--out",
        type=str,
        default=None,
        help="Output path for the Markdown report (default: no Markdown output).",
    )
    scan_parser.add_argument(
        "--json",
        type=str,
        default=None,
        dest="json_out",
        help="Output path for the machine-readable JSON map.",
    )

    # plan command
    plan_parser = subparsers.add_parser("plan", help="Generate a module-level fusion plan from a JSON map")
    plan_parser.add_argument(
        "--map",
        required=True,
        type=str,
        help="Path to the JSON project map generated by 'aetherfusion scan --json'.",
    )
    plan_parser.add_argument(
        "--module",
        required=True,
        type=str,
        help="Module name to plan for (must exist in fusion_plan_candidates).",
    )
    plan_parser.add_argument(
        "--out",
        type=str,
        default=None,
        help="Output path for the Markdown fusion plan.",
    )
    plan_parser.add_argument(
        "--json",
        type=str,
        default=None,
        dest="json_out",
        help="Output path for the JSON fusion plan.",
    )

    # patch command
    patch_parser = subparsers.add_parser(
        "patch",
        help="Generate a dry-run patch preview from a fusion plan (v0.3 — no files modified)",
    )
    patch_parser.add_argument(
        "--plan",
        required=True,
        type=str,
        help="Path to the v0.2 fusion plan JSON (from 'aetherfusion plan --json').",
    )
    patch_parser.add_argument(
        "--out",
        type=str,
        default=None,
        help="Output path for the Markdown patch preview.",
    )
    patch_parser.add_argument(
        "--json",
        type=str,
        default=None,
        dest="json_out",
        help="Output path for the machine-readable JSON patch manifest.",
    )
    patch_parser.add_argument(
        "--diff",
        type=str,
        default=None,
        dest="diff_out",
        help="Output path for the unified diff file (add_file operations only).",
    )
    patch_parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        required=False,
        help="REQUIRED for v0.3 — patch command only operates in dry-run mode.",
    )

    # apply command
    apply_parser = subparsers.add_parser(
        "apply",
        help="Apply add_file operations from a patch manifest (v0.4 — confirmed apply only)",
    )
    apply_parser.add_argument(
        "--patch",
        required=True,
        type=str,
        help="Path to the v0.3 patch manifest JSON (from 'aetherfusion patch --json').",
    )
    apply_parser.add_argument(
        "--confirm",
        action="store_true",
        default=False,
        help="REQUIRED — confirms intent to apply add_file operations.",
    )
    apply_parser.add_argument(
        "--out",
        type=str,
        default=None,
        help="Output path for the Markdown apply report.",
    )
    apply_parser.add_argument(
        "--json",
        type=str,
        default=None,
        dest="json_out",
        help="Output path for the apply result JSON.",
    )
    apply_parser.add_argument(
        "--backup",
        type=str,
        default=None,
        dest="backup_path",
        help="Output path for the rollback/backup manifest (recommended).",
    )
    apply_parser.add_argument(
        "--audit",
        type=str,
        default=None,
        dest="audit_path",
        help="Path to the audit log JSONL file (default: reports/aetherfusion-audit.jsonl).",
    )

    # rollback command
    rollback_parser = subparsers.add_parser(
        "rollback",
        help="Roll back files created by apply using a rollback manifest (v0.4.5)",
    )
    rollback_parser.add_argument(
        "--manifest",
        required=True,
        type=str,
        help="Path to the v0.4 rollback manifest JSON.",
    )
    rollback_parser.add_argument(
        "--confirm",
        action="store_true",
        default=False,
        help="REQUIRED — confirms intent to delete files listed in the rollback manifest.",
    )
    rollback_parser.add_argument(
        "--out",
        type=str,
        default=None,
        help="Output path for the Markdown rollback report.",
    )
    rollback_parser.add_argument(
        "--json",
        type=str,
        default=None,
        dest="json_out",
        help="Output path for the rollback result JSON.",
    )
    rollback_parser.add_argument(
        "--audit",
        type=str,
        default=None,
        dest="audit_path",
        help="Path to the audit log JSONL file (default: reports/aetherfusion-audit.jsonl).",
    )

    # verify command
    verify_parser = subparsers.add_parser("verify", help="Run whitelisted verification commands on target project")
    verify_parser.add_argument(
        "--target",
        required=True,
        type=str,
        help="Path to the target project to verify.",
    )
    verify_parser.add_argument(
        "--commands",
        type=str,
        default=None,
        help="Comma-separated list of commands to run. If omitted, commands are auto-detected.",
    )
    verify_parser.add_argument(
        "--out",
        type=str,
        default=None,
        help="Output path for the Markdown verify report.",
    )
    verify_parser.add_argument(
        "--json",
        type=str,
        default=None,
        dest="json_out",
        help="Output path for the verify result JSON.",
    )
    verify_parser.add_argument(
        "--audit",
        type=str,
        default=None,
        dest="audit_path",
        help="Path to the audit log JSONL file (default: reports/aetherfusion-audit.jsonl).",
    )

    # repair-plan command
    repair_plan_parser = subparsers.add_parser(
        "repair-plan", help="Generate repair plan from verify result JSON"
    )
    repair_plan_parser.add_argument(
        "--verify",
        type=str,
        required=True,
        dest="verify_file",
        help="Path to the v0.5 verify result JSON.",
    )
    repair_plan_parser.add_argument(
        "--out",
        type=str,
        default=None,
        help="Output path for the Markdown repair plan.",
    )
    repair_plan_parser.add_argument(
        "--json",
        type=str,
        default=None,
        dest="json_out",
        help="Output path for the repair plan JSON.",
    )
    repair_plan_parser.add_argument(
        "--audit",
        type=str,
        default=None,
        dest="audit_path",
        help="Path to the audit log JSONL file (default: reports/aetherfusion-audit.jsonl).",
    )

    # import-fix-plan command
    import_fix_plan_parser = subparsers.add_parser(
        "import-fix-plan", help="Generate import/path fix plan from repair-plan JSON"
    )
    import_fix_plan_parser.add_argument(
        "--repair",
        type=str,
        required=True,
        dest="repair_file",
        help="Path to the v0.6 repair-plan JSON.",
    )
    import_fix_plan_parser.add_argument(
        "--target",
        type=str,
        required=True,
        dest="target_path",
        help="Path to the target project root.",
    )
    import_fix_plan_parser.add_argument(
        "--patch",
        type=str,
        default=None,
        dest="patch_file",
        help="Optional: path to v0.3 patch manifest JSON.",
    )
    import_fix_plan_parser.add_argument(
        "--apply",
        type=str,
        default=None,
        dest="apply_file",
        help="Optional: path to v0.4 apply result JSON.",
    )
    import_fix_plan_parser.add_argument(
        "--json",
        type=str,
        default=None,
        dest="json_out",
        help="Output path for the import fix plan JSON.",
    )
    import_fix_plan_parser.add_argument(
        "--out",
        type=str,
        default=None,
        help="Output path for the Markdown import fix plan.",
    )
    import_fix_plan_parser.add_argument(
        "--audit",
        type=str,
        default=None,
        dest="audit_path",
        help="Path to the audit log JSONL file (default: reports/aetherfusion-audit.jsonl).",
    )

    # dependency-plan command
    dependency_plan_parser = subparsers.add_parser(
        "dependency-plan", help="Generate dependency update plan from repair-plan / import-fix-plan"
    )
    dependency_plan_parser.add_argument(
        "--repair",
        type=str,
        required=True,
        dest="repair_file",
        help="Path to the v0.6 repair-plan JSON.",
    )
    dependency_plan_parser.add_argument(
        "--import-fix",
        type=str,
        default=None,
        dest="import_fix_file",
        help="Optional: path to v0.7 import-fix-plan JSON.",
    )
    dependency_plan_parser.add_argument(
        "--target",
        type=str,
        required=True,
        dest="target_path",
        help="Path to the target project root.",
    )
    dependency_plan_parser.add_argument(
        "--source",
        type=str,
        required=True,
        dest="source_path",
        help="Path to the source project root.",
    )
    dependency_plan_parser.add_argument(
        "--json",
        type=str,
        default=None,
        dest="json_out",
        help="Output path for the dependency plan JSON.",
    )
    dependency_plan_parser.add_argument(
        "--out",
        type=str,
        default=None,
        help="Output path for the Markdown dependency plan.",
    )
    dependency_plan_parser.add_argument(
        "--audit",
        type=str,
        default=None,
        dest="audit_path",
        help="Path to the audit log JSONL file (default: reports/aetherfusion-audit.jsonl).",
    )

    # fusion-session command (v1.0)
    fusion_session_parser = subparsers.add_parser(
        "fusion-session",
        help="Run a full fusion session: scan → plan → patch → optional apply → optional verify",
    )
    fusion_session_parser.add_argument(
        "--source",
        type=str,
        required=True,
        help="Path to the source project.",
    )
    fusion_session_parser.add_argument(
        "--target",
        type=str,
        required=True,
        help="Path to the target project.",
    )
    fusion_session_parser.add_argument(
        "--modules",
        type=str,
        required=True,
        help="Comma-separated list of module names to process (e.g. utils,lib).",
    )
    fusion_session_parser.add_argument(
        "--reports",
        type=str,
        required=True,
        dest="reports_dir",
        help="Directory for all generated session reports and artifacts.",
    )
    fusion_session_parser.add_argument(
        "--mode",
        type=str,
        default="safe",
        help="Session mode (default: safe).",
    )
    fusion_session_parser.add_argument(
        "--apply-confirm",
        action="store_true",
        default=False,
        help="Apply patches after dry-run (default: skipped).",
    )
    fusion_session_parser.add_argument(
        "--verify",
        action="store_true",
        default=False,
        help="Run verification after apply (default: skipped).",
    )
    fusion_session_parser.add_argument(
        "--audit",
        type=str,
        default=None,
        dest="audit_path",
        help="Path to the audit log JSONL file (default: reports-dir/aetherfusion-audit.jsonl).",
    )

    args = parser.parse_args(argv if argv is not None else sys.argv[1:])

    if args.command is None:
        parser.print_help()
        sys.exit(1)

    if args.command == "scan":
        _run_scan(args)
    elif args.command == "plan":
        _run_plan(args)
    elif args.command == "patch":
        _run_patch(args)
    elif args.command == "apply":
        _run_apply(args)
    elif args.command == "rollback":
        _run_rollback(args)
    elif args.command == "verify":
        _run_verify(args)
    elif args.command == "repair-plan":
        _run_repair_plan(args)
    elif args.command == "import-fix-plan":
        _run_import_fix_plan(args)
    elif args.command == "dependency-plan":
        _run_dependency_plan(args)
    elif args.command == "fusion-session":
        _run_fusion_session(args)


def _run_scan(args: argparse.Namespace) -> None:
    """Execute the scan command.

    Supports:
    - --out:  Markdown human-readable report
    - --json: machine-readable JSON map for downstream agent consumption
    At least one of --out or --json must be provided.
    """
    source_path = Path(args.source).resolve()
    target_path = Path(args.target).resolve()

    # Validate inputs
    if not source_path.is_dir():
        print(f"Error: Source path is not a directory: {source_path}", file=sys.stderr)
        sys.exit(1)
    if not target_path.is_dir():
        print(f"Error: Target path is not a directory: {target_path}", file=sys.stderr)
        sys.exit(1)

    # Require at least one output
    if args.out is None and args.json_out is None:
        print("Error: No output specified. Provide --out and/or --json.", file=sys.stderr)
        sys.exit(1)

    # --- Git status checks (read-only) ---
    source_git = check_git_status(source_path)
    target_git = check_git_status(target_path)
    _print_git_status("source", source_git)
    _print_git_status("target", target_git)

    # --- Scan ---
    print(f"Scanning source: {source_path}")
    source_info = ProjectAnalyzer(source_path).analyze()
    print(f"  -> {source_info.file_count} files, {source_info.dir_count} dirs, "
          f"{len(source_info.config_files_detected)} configs")

    print(f"Scanning target: {target_path}")
    target_info = ProjectAnalyzer(target_path).analyze()
    print(f"  -> {target_info.file_count} files, {target_info.dir_count} dirs, "
          f"{len(target_info.config_files_detected)} configs")

    # --- Markdown report ---
    if args.out:
        out_path = Path(args.out).resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        print(f"Generating Markdown report...")
        report = generate_report(source_info, target_info)
        out_path.write_text(report, encoding="utf-8")
        print(f"  -> {out_path}")

    # --- JSON map ---
    if args.json_out:
        json_path = Path(args.json_out).resolve()
        print(f"Generating JSON map...")
        data = generate_json_map(source_info, target_info)
        write_json_map(json_path, data)
        print(f"  -> {json_path}")

    print("Done.")


def _print_git_status(label: str, git_result: dict) -> None:
    """Print a concise git status line for the CLI."""
    status = git_result["status"]
    branch = git_result.get("branch")
    changed = len(git_result.get("changed_files", []))

    if status == "not_git_repo":
        print(f"Git [{label}]: not a git repository")
    elif status == "clean":
        print(f"Git [{label}]: clean (branch: {branch})")
    elif status == "dirty":
        print(f"Git [{label}]: dirty — {changed} changed file(s) (branch: {branch})")
    else:
        msg = git_result.get("error_message", "unknown error")
        print(f"Git [{label}]: error — {msg}")


def _run_plan(args: argparse.Namespace) -> None:
    """Execute the plan command.

    Loads a JSON project map and generates a module-level fusion plan.
    At least one of --out or --json must be specified.
    Exits with code 1 if the module is not found or the map is invalid.
    """
    map_path = Path(args.map).resolve()

    if not map_path.is_file():
        print(f"Error: JSON map not found: {map_path}", file=sys.stderr)
        sys.exit(1)

    if args.out is None and args.json_out is None:
        print("Error: No output specified. Provide --out and/or --json.", file=sys.stderr)
        sys.exit(1)

    print(f"Loading project map: {map_path}")
    try:
        plan = generate_fusion_plan(map_path, args.module)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in map file: {e}", file=sys.stderr)
        sys.exit(1)
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    module_name = plan.get("module_name", "?")
    risk_level = plan.get("risk_level", "?")
    strategy = plan.get("strategy", "?")

    print(f"  -> Module: {module_name}")
    print(f"  -> Risk: {risk_level}, Strategy: {strategy}")

    # Markdown plan
    if args.out:
        out_path = Path(args.out).resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        report = generate_plan_report(plan)
        out_path.write_text(report, encoding="utf-8")
        print(f"  -> Markdown plan: {out_path}")

    # JSON plan
    if args.json_out:
        json_path = Path(args.json_out).resolve()
        write_plan_json(json_path, plan)
        print(f"  -> JSON plan: {json_path}")

    print("Done.")


def _run_patch(args: argparse.Namespace) -> None:
    """Execute the patch command.

    Generates a dry-run patch preview from a fusion plan JSON.
    Requires --dry-run; refuses to run otherwise.
    At least one of --out, --json, or --diff must be specified.
    """
    # Enforce --dry-run
    if not args.dry_run:
        print(
            "Error: The 'patch' command requires --dry-run. "
            "v0.3 only supports dry-run mode; no files are modified.",
            file=sys.stderr,
        )
        sys.exit(1)

    if args.out is None and args.json_out is None and args.diff_out is None:
        print(
            "Error: No output specified. Provide --out, --json, and/or --diff.",
            file=sys.stderr,
        )
        sys.exit(1)

    plan_path = Path(args.plan).resolve()

    if not plan_path.is_file():
        print(f"Error: Fusion plan not found: {plan_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Loading fusion plan: {plan_path}")

    try:
        manifest = generate_dry_run_patch(plan_path)
    except (FileNotFoundError, ValueError) as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in plan file: {e}", file=sys.stderr)
        sys.exit(1)

    summary = manifest.get("summary", {})
    print(f"  -> Module: {manifest.get('module_name', '?')}")
    print(f"  -> Files to add: {summary.get('files_to_add', 0)}")
    print(f"  -> Files conflicted: {summary.get('files_conflicted', 0)}")
    print(f"  -> Files skipped: {summary.get('files_skipped', 0)}")
    print(f"  -> Mode: {manifest.get('mode', '?')}")

    # Markdown patch preview
    if args.out:
        out_path = Path(args.out).resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        report = generate_patch_report(manifest)
        out_path.write_text(report, encoding="utf-8")
        print(f"  -> Markdown preview: {out_path}")

    # JSON patch manifest
    if args.json_out:
        json_path = Path(args.json_out).resolve()
        write_patch_json(json_path, manifest)
        print(f"  -> JSON manifest: {json_path}")

    # Diff output
    if args.diff_out:
        diff_path = Path(args.diff_out).resolve()
        generate_diff(manifest, diff_path)
        print(f"  -> Diff file: {diff_path}")

    print("Done. No source or target files were modified.")


def _run_apply(args: argparse.Namespace) -> None:
    """Execute the apply command.

    Applies only add_file operations from a patch manifest.
    Requires --confirm; refuses to run otherwise.
    At least one of --out or --json must be specified.
    Writes a rollback manifest if --backup is provided.
    """
    # Enforce --confirm
    if not args.confirm:
        print(
            "Error: The 'apply' command requires --confirm. "
            "This ensures you have explicitly acknowledged the intent to modify "
            "the target project by copying new files into it.",
            file=sys.stderr,
        )
        sys.exit(1)

    if args.out is None and args.json_out is None:
        print(
            "Error: No output specified. Provide --out and/or --json.",
            file=sys.stderr,
        )
        sys.exit(1)

    patch_path = Path(args.patch).resolve()

    if not patch_path.is_file():
        print(f"Error: Patch manifest not found: {patch_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Applying patch manifest: {patch_path}")

    backup_path = Path(args.backup_path).resolve() if args.backup_path else None

    try:
        result = apply_patch(patch_path, backup_path)
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in patch manifest: {e}", file=sys.stderr)
        sys.exit(1)

    summary = result.get("summary", {})
    print(f"  -> Module: {result.get('module_name', '?')}")
    print(f"  -> Mode: {result.get('mode', '?')}")
    print(f"  -> Applied: {summary.get('files_applied', 0)}")
    print(f"  -> Skipped: {summary.get('files_skipped', 0)}")
    print(f"  -> Blocked: {summary.get('files_blocked', 0)}")
    print(f"  -> Failed:  {summary.get('files_failed', 0)}")
    if result.get("rollback_manifest_path"):
        print(f"  -> Rollback manifest: {result['rollback_manifest_path']}")

    # Markdown apply report
    if args.out:
        out_path = Path(args.out).resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        report = generate_apply_report(result)
        out_path.write_text(report, encoding="utf-8")
        print(f"  -> Markdown report: {out_path}")

    # JSON apply result
    if args.json_out:
        json_path = Path(args.json_out).resolve()
        write_apply_json(json_path, result)
        print(f"  -> JSON result: {json_path}")

    # Audit logging
    audit_path = Path(args.audit_path) if args.audit_path else Path("reports/aetherfusion-audit.jsonl")
    event = make_apply_event(
        result,
        str(patch_path.resolve()),
        str(Path(args.json_out).resolve()) if args.json_out else "",
    )
    ok = log_audit_event(audit_path, event)
    if not ok:
        print(f"  -> WARNING: Failed to write audit log to {audit_path}")

    print("Done.")


def _run_rollback(args: argparse.Namespace) -> None:
    """Execute the rollback command.

    Reads a v0.4 rollback manifest and deletes the files listed in
    its `created_files`.  Requires --confirm.  Writes optional JSON
    result and Markdown report.  Appends an audit event on success.
    """
    # Enforce --confirm
    if not args.confirm:
        print(
            "Error: The 'rollback' command requires --confirm. "
            "This ensures you have explicitly acknowledged the intent "
            "to DELETE files from the target project.",
            file=sys.stderr,
        )
        sys.exit(1)

    if args.out is None and args.json_out is None:
        print(
            "Error: No output specified. Provide --out and/or --json.",
            file=sys.stderr,
        )
        sys.exit(1)

    manifest_path = Path(args.manifest).resolve()

    if not manifest_path.is_file():
        print(f"Error: Rollback manifest not found: {manifest_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Rolling back from manifest: {manifest_path}")

    try:
        result = rollback_apply(manifest_path)
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in rollback manifest: {e}", file=sys.stderr)
        sys.exit(1)

    summary = result.get("summary", {})
    print(f"  -> Module: {result.get('module_name', '?')}")
    print(f"  -> Mode: {result.get('mode', '?')}")
    print(f"  -> Deleted: {summary.get('files_deleted', 0)}")
    print(f"  -> Already missing: {summary.get('files_already_missing', 0)}")
    print(f"  -> Blocked: {summary.get('files_blocked', 0)}")
    print(f"  -> Failed:  {summary.get('files_failed', 0)}")

    # Markdown rollback report
    if args.out:
        out_path = Path(args.out).resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        report = generate_rollback_report(result)
        out_path.write_text(report, encoding="utf-8")
        print(f"  -> Markdown report: {out_path}")

    # JSON rollback result
    if args.json_out:
        json_path = Path(args.json_out).resolve()
        write_rollback_json(json_path, result)
        print(f"  -> JSON result: {json_path}")

    # Audit logging
    audit_path = Path(args.audit_path) if args.audit_path else Path("reports/aetherfusion-audit.jsonl")
    event = make_rollback_event(
        result,
        str(manifest_path.resolve()),
        str(Path(args.json_out).resolve()) if args.json_out else "",
    )
    ok = log_audit_event(audit_path, event)
    if not ok:
        print(f"  -> WARNING: Failed to write audit log to {audit_path}")

    print("Done.")


def _run_verify(args: argparse.Namespace) -> None:
    """Execute the verify command.

    Runs whitelisted verification commands (build/test/lint/typecheck)
    on the target project. Auto-detects commands unless --commands is
    provided. Writes JSONL audit event on completion.
    """
    target = Path(args.target).resolve()

    if not target.exists():
        print(f"Error: Target path does not exist: {target}", file=sys.stderr)
        sys.exit(1)
    if not target.is_dir():
        print(f"Error: Target path is not a directory: {target}", file=sys.stderr)
        sys.exit(1)

    if args.out is None and args.json_out is None:
        print("Error: No output specified. Provide --out and/or --json.", file=sys.stderr)
        sys.exit(1)

    commands = None
    if args.commands:
        commands = [cmd.strip() for cmd in args.commands.split(",") if cmd.strip()]

    print(f"Verifying target: {target}")
    if commands:
        print(f"  -> Commands: {', '.join(commands)}")

    result = run_verify(target, commands=commands)

    summary = result.get("summary", {})
    print(f"  -> Detected: {', '.join(result.get('detected_stack', [])) or 'none'}")
    print(
        f"  -> Total: {summary.get('total', 0)}  "
        f"Passed: {summary.get('passed', 0)}  "
        f"Failed: {summary.get('failed', 0)}  "
        f"Skipped: {summary.get('skipped', 0)}  "
        f"Timeout: {summary.get('timeout', 0)}  "
        f"Blocked: {summary.get('blocked', 0)}"
    )

    # Markdown verify report
    if args.out:
        out_path = Path(args.out).resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        report = generate_verify_report(result)
        out_path.write_text(report, encoding="utf-8")
        print(f"  -> Markdown report: {out_path}")

    # JSON verify result
    if args.json_out:
        json_path = Path(args.json_out).resolve()
        write_verify_json(json_path, result)
        print(f"  -> JSON result: {json_path}")

    # Audit logging
    audit_path = Path(args.audit_path) if args.audit_path else Path("reports/aetherfusion-audit.jsonl")
    event = make_verify_event(
        result,
        str(target),
        str(Path(args.json_out).resolve()) if args.json_out else "",
    )
    ok = log_audit_event(audit_path, event)
    if not ok:
        print(f"  -> WARNING: Failed to write audit log to {audit_path}")

    print("Done.")


def _run_repair_plan(args: argparse.Namespace) -> None:
    """Execute the repair-plan subcommand."""
    # Require at least one output
    if not args.out and not args.json_out:
        print("Error: At least one of --out or --json is required.", file=sys.stderr)
        sys.exit(1)

    verify_file = Path(args.verify_file).resolve()

    # Generate repair plan
    plan = generate_repair_plan(str(verify_file))

    summary = plan.get("summary", {})
    print(
        f"Repair plan for {plan.get('source_verify_file', '?')}:  "
        f"Failed: {summary.get('total_failed_commands', 0)}  "
        f"Classified: {summary.get('total_classified_errors', 0)}  "
        f"Repair items: {summary.get('total_repair_items', 0)}"
    )

    # Markdown repair plan
    if args.out:
        out_path = Path(args.out).resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        report = generate_repair_report(plan)
        out_path.write_text(report, encoding="utf-8")
        print(f"  -> Markdown report: {out_path}")

    # JSON repair plan
    if args.json_out:
        json_path = Path(args.json_out).resolve()
        write_repair_json(json_path, plan)
        print(f"  -> JSON plan: {json_path}")

    # Audit logging
    audit_path = Path(args.audit_path) if args.audit_path else Path("reports/aetherfusion-audit.jsonl")
    event = make_repair_plan_event(
        plan,
        str(verify_file),
        str(Path(args.json_out).resolve()) if args.json_out else "",
    )
    ok = log_audit_event(audit_path, event)
    if not ok:
        print(f"  -> WARNING: Failed to write audit log to {audit_path}")

    print("Done.")


def _run_import_fix_plan(args: argparse.Namespace) -> None:
    """Execute the import-fix-plan subcommand."""
    # Require at least one output
    if not args.out and not args.json_out:
        print("Error: At least one of --out or --json is required.", file=sys.stderr)
        sys.exit(1)

    repair_file = Path(args.repair_file).resolve()
    target_path = Path(args.target_path).resolve()
    patch_file = Path(args.patch_file).resolve() if args.patch_file else None
    apply_file = Path(args.apply_file).resolve() if args.apply_file else None

    # Generate import fix plan
    try:
        plan = generate_import_fix_plan(repair_file, target_path, patch_file, apply_file)
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except NotADirectoryError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in repair plan: {e}", file=sys.stderr)
        sys.exit(1)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    summary = plan.get("summary", {})
    print(
        f"Import fix plan:  "
        f"Extracted: {summary.get('total_extracted_import_errors', 0)}  "
        f"Candidates: {summary.get('total_fix_candidates', 0)}"
    )

    by_kind = summary.get("by_suspected_kind", {})
    if by_kind:
        kinds = ", ".join(f"{k}={v}" for k, v in sorted(by_kind.items()))
        print(f"  -> By kind: {kinds}")

    # Markdown import fix plan
    if args.out:
        out_path = Path(args.out).resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        report = generate_import_fix_report(plan)
        out_path.write_text(report, encoding="utf-8")
        print(f"  -> Markdown report: {out_path}")

    # JSON import fix plan
    if args.json_out:
        json_path = Path(args.json_out).resolve()
        write_import_fix_json(json_path, plan)
        print(f"  -> JSON plan: {json_path}")

    # Audit logging
    audit_path = Path(args.audit_path) if args.audit_path else Path("reports/aetherfusion-audit.jsonl")
    event = make_import_fix_plan_event(
        plan,
        str(repair_file),
        str(target_path),
        str(Path(args.json_out).resolve()) if args.json_out else "",
    )
    ok = log_audit_event(audit_path, event)
    if not ok:
        print(f"  -> WARNING: Failed to write audit log to {audit_path}")

    print("Done.")


def _run_dependency_plan(args: argparse.Namespace) -> None:
    """Execute the dependency-plan subcommand."""
    # Require at least one output
    if not args.out and not args.json_out:
        print("Error: At least one of --out or --json is required.", file=sys.stderr)
        sys.exit(1)

    repair_file = Path(args.repair_file).resolve()
    target_path = Path(args.target_path).resolve()
    source_path = Path(args.source_path).resolve()
    import_fix_file = Path(args.import_fix_file).resolve() if args.import_fix_file else None

    # Generate dependency plan
    try:
        plan = generate_dependency_plan(repair_file, target_path, source_path, import_fix_file)
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except NotADirectoryError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in input file: {e}", file=sys.stderr)
        sys.exit(1)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    summary = plan.get("summary", {})
    print(
        f"Dependency plan:  "
        f"Extracted: {summary.get('total_extracted_dependency_errors', 0)}  "
        f"Candidates: {summary.get('total_dependency_candidates', 0)}"
    )

    print(
        f"  -> Add to target: {summary.get('add_to_target', 0)}  "
        f"Ver conflict: {summary.get('review_version_conflict', 0)}  "
        f"Manual research: {summary.get('manual_research', 0)}  "
        f"Builtin/stdlib skipped: {summary.get('builtin_or_stdlib_skipped', 0)}"
    )

    # Markdown dependency plan
    if args.out:
        out_path = Path(args.out).resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        report = generate_dependency_report(plan)
        out_path.write_text(report, encoding="utf-8")
        print(f"  -> Markdown report: {out_path}")

    # JSON dependency plan
    if args.json_out:
        json_path = Path(args.json_out).resolve()
        write_dependency_json(json_path, plan)
        print(f"  -> JSON plan: {json_path}")

    # Audit logging
    audit_path = Path(args.audit_path) if args.audit_path else Path("reports/aetherfusion-audit.jsonl")
    result_json = str(Path(args.json_out).resolve()) if args.json_out else ""
    event = make_dependency_plan_event(
        plan,
        str(repair_file),
        str(target_path),
        str(source_path),
        result_json,
    )
    ok = log_audit_event(audit_path, event)
    if not ok:
        print(f"  -> WARNING: Failed to write audit log to {audit_path}")

    print("Done.")


def _run_fusion_session(args: argparse.Namespace) -> None:
    """Execute the fusion-session subcommand."""
    source_path = Path(args.source).resolve()
    target_path = Path(args.target).resolve()
    modules = [m.strip() for m in args.modules.split(",") if m.strip()]
    reports_dir = Path(args.reports_dir).resolve()
    audit_path = args.audit_path or ""

    try:
        result = run_fusion_session(
            source_path=str(source_path),
            target_path=str(target_path),
            modules=modules,
            reports_dir=str(reports_dir),
            mode=args.mode,
            apply_confirm=args.apply_confirm,
            verify=args.verify,
            audit_path=audit_path,
        )
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except RuntimeError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    # Print session summary
    module_results = result.get("module_results", {})
    total = len(modules)
    failed = sum(1 for v in module_results.values() if isinstance(v, dict) and v.get("status") == "failed")
    succeeded = total - failed

    print(f"\nFusion session complete: {result.get('session_id', '?')}")
    print(f"  Modules: {succeeded}/{total} succeeded")
    if failed:
        failed_names = [k for k, v in module_results.items() if isinstance(v, dict) and v.get("status") == "failed"]
        print(f"  Failed: {', '.join(failed_names)}")

    if result.get("verify_summary") and result["verify_summary"] is not None:
        vsum = result["verify_summary"]
        print(f"  Verify: {'PASSED' if vsum.get('passed') else 'FAILED'}")

    if result.get("diagnostic_plans", {}).get("generated"):
        plans = result["diagnostic_plans"]["generated"]
        print(f"  Diagnostic plans: {', '.join(plans)}")

    session_json_path = result.get("artifacts", {})
    print(f"  Session JSON: {reports_dir / 'fusion-session.json'}")
    print(f"  Session MD: {reports_dir / 'fusion-session.md'}")
    print(f"  Artifact index: {reports_dir / 'artifact-index.json'}")
    print(f"  Next action: {result.get('next_recommended_action', 'N/A')}")

    print("Done.")


if __name__ == "__main__":
    main()