"""Markdown reporter for import fix plans.

Generates a human-readable import fix plan report with sections for
summary, extracted import errors, fix candidates, automation
eligibility, related files, blocked actions, and next command.
"""

from typing import Any


_KIND_LABELS: dict[str, str] = {
    "missing_local_file": "Missing local file",
    "wrong_relative_path": "Wrong relative path",
    "missing_alias_config": "Missing alias config",
    "missing_index_export": "Missing index/barrel export",
    "source_only_dependency": "Source-only dependency",
    "package_missing": "Package not installed",
    "unresolved_unknown": "Unresolved / Unknown",
}


def generate_import_fix_report(plan: dict[str, Any]) -> str:
    """Generate a Markdown import fix plan report.

    Args:
        plan: Import fix plan dict from generate_import_fix_plan.

    Returns:
        Markdown string for the report.
    """
    lines: list[str] = []

    version = plan.get("import_fix_plan_version", "?")
    source = plan.get("source_repair_file", "?")
    target = plan.get("target_path", "?")
    summary = plan.get("summary", {})
    extracted = plan.get("extracted_import_errors", [])
    candidates = plan.get("fix_candidates", [])
    blocked = plan.get("blocked_actions", [])
    next_cmd = plan.get("next_recommended_command", "")

    # -- Title ------------------------------------------------------------
    lines.append("# AetherFusion Import Fix Plan")
    lines.append("")
    lines.append(f"> **Generated by AetherFusion v{version}**")
    lines.append(f"> Source repair file: `{source}`")
    lines.append(f"> Target project: `{target}`")
    lines.append("")
    lines.append("> **v0.7 Import Fix Plan is read-only.** No source or target files were modified.")
    lines.append("")

    # -- 1. Summary -------------------------------------------------------
    lines.append("## 1. Summary")
    lines.append("")
    lines.append(f"| Metric | Count |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Import errors extracted | {summary.get('total_extracted_import_errors', 0)} |")
    lines.append(f"| Fix candidates generated | {summary.get('total_fix_candidates', 0)} |")
    lines.append("")

    # By kind
    by_kind = summary.get("by_suspected_kind", {})
    if by_kind:
        lines.append("### By Suspected Kind")
        lines.append("")
        lines.append("| Kind | Count |")
        lines.append("|------|-------|")
        for kind, count in sorted(by_kind.items(), key=lambda x: -x[1]):
            label = _KIND_LABELS.get(kind, kind)
            lines.append(f"| {label} | {count} |")
        lines.append("")

    # By automation
    by_auto = summary.get("by_automation_eligibility", {})
    if by_auto:
        lines.append("### By Automation Eligibility")
        lines.append("")
        lines.append("| Eligibility | Count |")
        lines.append("|--------------|-------|")
        for key in ["safe_auto_candidate", "plan_only", "manual_only"]:
            if key in by_auto:
                lines.append(f"| {key} | {by_auto[key]} |")
        lines.append("")

    # By risk
    by_risk = summary.get("by_risk_level", {})
    if by_risk:
        lines.append("### By Risk Level")
        lines.append("")
        lines.append("| Risk | Count |")
        lines.append("|------|-------|")
        for key in ["low", "medium", "high"]:
            if key in by_risk:
                lines.append(f"| {key} | {by_risk[key]} |")
        lines.append("")

    # -- 2. Extracted Import Errors ---------------------------------------
    lines.append("## 2. Extracted Import Errors")
    lines.append("")
    if not extracted:
        lines.append("No `missing_import` errors found in the repair plan.")
        lines.append("")
    else:
        for i, err in enumerate(extracted, 1):
            mod = err.get("missing_module", "?")
            cmd = err.get("command", "?")
            evidence = err.get("evidence", "")[:200]
            lines.append(f"### 2.{i}. `{mod}`")
            lines.append("")
            lines.append(f"- **Command**: `{cmd}`")
            lines.append(f"- **Evidence**: `{evidence}`")
            lines.append("")

    # -- 3. Fix Candidates ------------------------------------------------
    lines.append("## 3. Fix Candidates")
    lines.append("")
    if not candidates:
        lines.append("*No fix candidates generated.*")
        lines.append("")
    else:
        for i, fc in enumerate(candidates, 1):
            mod = fc.get("missing_module", "?")
            kind = fc.get("suspected_import_kind", "?")
            kind_label = _KIND_LABELS.get(kind, kind)
            lines.append(f"### 3.{i}. `{mod}` — {kind_label}")
            lines.append("")
            lines.append(f"| Field | Value |")
            lines.append(f"|-------|-------|")
            lines.append(f"| Missing module | `{mod}` |")
            lines.append(f"| Originating command | `{fc.get('originating_command', '?')}` |")
            lines.append(f"| Suspected kind | {kind_label} |")
            lines.append(f"| Confidence | {fc.get('confidence', 0)}% |")
            lines.append(f"| Automation eligibility | {fc.get('automation_eligibility', '?')} |")
            lines.append(f"| Risk level | {fc.get('risk_level', '?')} |")
            lines.append("")
            lines.append(f"**Likely cause**: {fc.get('likely_cause', '')}")
            lines.append("")
            lines.append(f"**Suggested action**: {fc.get('suggested_action', '')}")
            lines.append("")
            related = fc.get("related_files", [])
            if related:
                lines.append("**Related files**:")
                for rf in related:
                    lines.append(f"- `{rf}`")
                lines.append("")

    # -- 4. Automation Eligibility ----------------------------------------
    lines.append("## 4. Automation Eligibility")
    lines.append("")
    lines.append("| Candidate | Kind | Eligibility |")
    lines.append("|-----------|------|-------------|")
    for i, fc in enumerate(candidates, 1):
        mod = fc.get("missing_module", "?")
        kind = fc.get("suspected_import_kind", "?")
        auto = fc.get("automation_eligibility", "?")
        lines.append(f"| {i}. `{mod}` | {_KIND_LABELS.get(kind, kind)} | {auto} |")
    lines.append("")

    # -- 5. Related Files -------------------------------------------------
    lines.append("## 5. Related Files")
    lines.append("")
    all_related: set[str] = set()
    for fc in candidates:
        for rf in fc.get("related_files", []):
            all_related.add(rf)
    if all_related:
        for rf in sorted(all_related):
            lines.append(f"- `{rf}`")
    else:
        lines.append("*No related files identified.*")
    lines.append("")

    # -- 6. Blocked Actions -----------------------------------------------
    lines.append("## 6. Blocked Actions")
    lines.append("")
    for action in blocked:
        lines.append(f"- {action}")
    lines.append("")

    # -- 7. Next Recommended Command --------------------------------------
    lines.append("## 7. Next Recommended Command")
    lines.append("")
    lines.append(f"```bash")
    lines.append(f"{next_cmd}")
    lines.append(f"```")
    lines.append("")

    return "\n".join(lines)