"""Rollback Markdown reporter — generates human-readable rollback report."""

from typing import Any


def generate_rollback_report(result: dict[str, Any]) -> str:
    """Generate a Markdown rollback report from the rollback result.

    Args:
        result: Rollback result dict from safe_rollback.rollback_apply.

    Returns:
        Markdown string.
    """
    summary = result.get("summary", {})
    module_name = result.get("module_name", "?")
    target_path = result.get("target_match_path", "?")
    manifest_file = result.get("manifest_file", "?")

    deleted = result.get("files_deleted", [])
    already_missing = result.get("files_already_missing", [])
    blocked = result.get("files_blocked", [])
    failed = result.get("files_failed", [])

    lines: list[str] = []

    lines.append(f"# AetherFusion Rollback Report — `{module_name}`")
    lines.append("")
    lines.append("> **v0.4.5 Rollback: only deletes files recorded in the rollback manifest.**")
    lines.append("> No directories were deleted. No config files were removed unless explicitly created by apply.")
    lines.append(f"> Rollback version: `{result.get('rollback_version', '?')}`")
    lines.append(f"> Mode: `{result.get('mode', '?')}`")
    lines.append("")

    # Summary
    lines.append("## 1. Summary")
    lines.append("")
    lines.append("| Metric | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| Files deleted | {summary.get('files_deleted', 0)} |")
    lines.append(f"| Files already missing | {summary.get('files_already_missing', 0)} |")
    lines.append(f"| Files blocked | {summary.get('files_blocked', 0)} |")
    lines.append(f"| Files failed | {summary.get('files_failed', 0)} |")
    lines.append("")
    lines.append(f"- **Module**: `{module_name}`")
    lines.append(f"- **Target**: `{target_path}`")
    lines.append(f"- **Manifest**: `{manifest_file}`")
    lines.append("")

    # Files deleted
    if deleted:
        lines.append("## 2. Files Deleted")
        lines.append("")
        lines.append("| # | Path |")
        lines.append("|---|------|")
        for i, path in enumerate(deleted, 1):
            lines.append(f"| {i} | `{path}` |")
        lines.append("")

    # Files already missing
    if already_missing:
        lines.append("## 3. Files Already Missing")
        lines.append("")
        lines.append("These files were recorded in the manifest but no longer exist on disk.")
        lines.append("")
        lines.append("| # | Path | Reason |")
        lines.append("|---|------|--------|")
        for i, f in enumerate(already_missing, 1):
            lines.append(f"| {i} | `{f.get('path', '?')}` | {f.get('reason', '?')} |")
        lines.append("")

    # Files blocked
    if blocked:
        lines.append("## 4. Files Blocked")
        lines.append("")
        lines.append("These files were blocked by safety checks and were not deleted.")
        lines.append("")
        lines.append("| # | Path | Reason |")
        lines.append("|---|------|--------|")
        for i, f in enumerate(blocked, 1):
            lines.append(f"| {i} | `{f.get('path', '?')}` | {f.get('reason', '?')} |")
        lines.append("")

    # Files failed
    if failed:
        lines.append("## 5. Files Failed")
        lines.append("")
        lines.append("These files could not be deleted due to OS-level errors.")
        lines.append("")
        lines.append("| # | Path | Reason |")
        lines.append("|---|------|--------|")
        for i, f in enumerate(failed, 1):
            lines.append(f"| {i} | `{f.get('path', '?')}` | {f.get('reason', '?')} |")
        lines.append("")

    # Next command
    lines.append("## 6. Next Recommended Command")
    lines.append("")
    lines.append("```bash")
    lines.append(result.get("next_recommended_command", "# (no recommendation available)"))
    lines.append("```")
    lines.append("")

    # Safety recap
    lines.append("---")
    lines.append("")
    lines.append("**Safety recap (v0.4.5):**")
    lines.append("- Only files listed in the rollback manifest's `created_files` were considered for deletion.")
    lines.append("- Path traversal attempts were blocked.")
    lines.append("- Protected config files (package.json, requirements.txt, pyproject.toml, etc.) were blocked.")
    lines.append("- Directories were not deleted.")
    lines.append("- No source project files were touched.")
    lines.append("")
    lines.append(f"_Generated by AetherFusion v{result.get('rollback_version', '?')}_")
    lines.append("")

    return "\n".join(lines)