"""Markdown reporter for verify results.

Generates a human-readable verification report with sections for
summary, detected project type, command results (passed / failed /
skipped / blocked), and next recommended command.
"""

from typing import Any


def generate_verify_report(result: dict[str, Any]) -> str:
    """Generate a Markdown verification report from a verify result dict.

    Args:
        result: Verify result dict from run_verify.

    Returns:
        Markdown string for the report.
    """
    lines: list[str] = []
    version = result.get("verify_version", "?")
    target = result.get("target_path", "?")
    detected = result.get("detected_stack", [])
    cmds_run = result.get("commands_run", [])
    summary = result.get("summary", {})
    results = result.get("results", [])

    # -- Title ----------------------------------------------------------------
    lines.append("# AetherFusion Verify Report")
    lines.append("")
    lines.append(f"> **Generated by AetherFusion v{version}**")
    lines.append(f"> Target: `{target}`")
    lines.append("")
    lines.append("> **v0.5 Verify is read-only.** No source or target files were modified.")
    lines.append("")

    # -- Summary --------------------------------------------------------------
    lines.append("## 1. Summary")
    lines.append("")
    total = summary.get("total", 0)
    passed = summary.get("passed", 0)
    failed = summary.get("failed", 0)
    skipped = summary.get("skipped", 0)
    timeout = summary.get("timeout", 0)
    blocked = summary.get("blocked", 0)
    lines.append(f"| Metric | Count |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total commands | {total} |")
    lines.append(f"| Passed | {passed} |")
    lines.append(f"| Failed | {failed} |")
    lines.append(f"| Skipped | {skipped} |")
    lines.append(f"| Timeout | {timeout} |")
    lines.append(f"| Blocked | {blocked} |")
    lines.append("")

    # -- Detected Project Type ------------------------------------------------
    lines.append("## 2. Detected Project Type")
    lines.append("")
    if detected:
        lines.append(f"**Tags:** {', '.join(detected)}")
    else:
        lines.append("No project type tags detected (no commands were auto-detected).")
    if cmds_run:
        lines.append("")
        lines.append(f"**Commands run:** {', '.join(cmds_run)}")
    lines.append("")

    # -- Commands Run ---------------------------------------------------------
    lines.append("## 3. Commands Run")
    lines.append("")

    if not results:
        lines.append("No commands were executed.")
        lines.append("")
    else:
        for i, r in enumerate(results, 1):
            cmd = r.get("command", "?")
            status = r.get("status", "?")
            exit_code = r.get("exit_code")
            duration = r.get("duration_ms", 0)
            reason = r.get("reason", "")

            lines.append(f"### 3.{i}. `{cmd}`")
            lines.append("")
            lines.append(f"- **Status:** {status}")
            if exit_code is not None:
                lines.append(f"- **Exit code:** {exit_code}")
            lines.append(f"- **Duration:** {duration} ms")
            if reason:
                lines.append(f"- **Reason:** {reason}")
            lines.append("")

    # -- Passed ---------------------------------------------------------------
    passed_results = [r for r in results if r["status"] == "passed"]
    if passed_results:
        lines.append("## 4. Passed")
        lines.append("")
        for r in passed_results:
            lines.append(f"- `{r['command']}` — {r['duration_ms']} ms")
        lines.append("")

    # -- Failed ---------------------------------------------------------------
    failed_results = [r for r in results if r["status"] == "failed"]
    if failed_results:
        lines.append("## 5. Failed")
        lines.append("")
        for r in failed_results:
            lines.append(f"- **`{r['command']}`** — exit code: {r.get('exit_code')} — {r.get('reason', '')}")
        lines.append("")

    # -- Skipped / Blocked ----------------------------------------------------
    skipped_results = [r for r in results if r["status"] == "skipped"]
    blocked_results = [r for r in results if r["status"] == "blocked"]
    timeout_results = [r for r in results if r["status"] == "timeout"]

    if skipped_results or blocked_results or timeout_results:
        lines.append("## 6. Skipped / Blocked / Timeout")
        lines.append("")
        for r in skipped_results:
            lines.append(f"- **`{r['command']}`** — skipped — {r.get('reason', '')}")
        for r in blocked_results:
            lines.append(f"- **`{r['command']}`** — blocked — {r.get('reason', '')}")
        for r in timeout_results:
            lines.append(f"- **`{r['command']}`** — timeout — {r.get('reason', '')}")
        lines.append("")

    # -- Error Output Tail ----------------------------------------------------
    error_results = [r for r in results if r["status"] in ("failed", "timeout")]
    if error_results:
        lines.append("## 7. Error Output Tail")
        lines.append("")
        for r in error_results:
            stderr = r.get("stderr_tail", "").strip()
            if stderr:
                lines.append(f"### `{r['command']}`")
                lines.append("")
                lines.append("```")
                lines.append(stderr[:1500])
                lines.append("```")
                lines.append("")

    # -- Next Recommended Command --------------------------------------------
    lines.append("## 8. Next Recommended Command")
    lines.append("")
    next_cmd = result.get("next_recommended_command", "")
    lines.append(f"```bash")
    lines.append(next_cmd)
    lines.append(f"```")
    lines.append("")

    return "\n".join(lines)